BETSLIP_RESULTS_DATE_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
SHARP_API_REQUEST_DATE_FORMAT = "%Y-%m-%d"
BOOK_REGIONS_HEDGE_FILENAME = "book_regions_hedge"

# Mongo DB
MONGO_ADMINS_COLLECTION = "admins"
MONGO_BETSLIPS_COLLECTION = "betslips"
MONGO_STATS_COLLECTION = "stats"
MONGO_USERS_COLLECTION = "users"
